"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import google.generativeai as genai

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-))5)9p_bk7yt+69l=mbd^0hhru1*xu#!+iewxm3bk^ai6(g=ki'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'translator',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Set gRPC env variables before loading Gemini client
os.environ["GRPC_DNS_RESOLVER"] = "native"
os.environ["GRPC_VERBOSITY"] = "debug"

# Load Gemini API key from env
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY") or st.secrets.get("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError("⚠️ Gemini API key not found. Set GEMINI_API_KEY in your environment.")

# Configure Gemini client
genai.configure(api_key=GEMINI_API_KEY)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
}

# ✅ Fonts directory
FONT_PATH = os.path.join(BASE_DIR, "translator", "fonts")

# ✅ Language → font mapping
FONTS = {
    "default": ("NotoSans", "NotoSans.ttf"),   # universal fallback
    "hi": ("NotoSansDevanagari", "NotoSansDevanagari.ttf"),
    "bn": ("NotoSansBengali", "NotoSansBengali.ttf"),
    "ta": ("NotoSansTamil", "NotoSansTamil.ttf"),
    "te": ("NotoSansTelugu", "NotoSansTelugu.ttf"),
    "gu": ("NotoSansGujarati", "NotoSansGujarati.ttf"),
    "mr": ("NotoSansDevanagari", "NotoSansDevanagari.ttf"),
    "pa": ("NotoSansGurmukhi", "NotoSansGurmukhi.ttf"),
    "zh": ("NotoSansSC", "NotoSansSC.ttf"),   # Simplified Chinese
    "ja": ("NotoSansJP", "NotoSansJP.ttf"),
    "ko": ("NotoSansKR", "NotoSansKR.ttf"),
    "ar": ("NotoNaskhArabic", "NotoNaskhArabic.ttf"),
    "ru": ("NotoSans", "NotoSans.ttf"),
    "kk": ("NotoSans", "NotoSans.ttf"),
    "fa": ("NotoNaskhArabic", "NotoNaskhArabic.ttf"),
    "ur": ("NotoNaskhArabic", "NotoNaskhArabic.ttf"),
    # Add more scripts if needed
}